## Part 1

You're minding your own business on a ship at sea when the overboard alarm goes off! You rush to see if you can help. Apparently, one of the Elves tripped and accidentally sent the sleigh keys flying into the ocean!

Before you know it, you're inside a submarine the Elves keep ready for situations like this. It's covered in Christmas lights (because of course it is), and it even has an experimental antenna that should be able to track the keys if you can boost its signal strength high enough; there's a little meter that indicates the antenna's signal strength by displaying 0-50 stars.

Your instincts tell you that in order to save Christmas, you'll need to get all fifty stars by December 25th.

Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

As the submarine drops below the surface of the ocean, it automatically performs a sonar sweep of the nearby sea floor. On a small screen, the sonar sweep report (your puzzle input) appears: each line is a measurement of the sea floor depth as the sweep looks further and further away from the submarine.

For example, suppose you had the following report:

- 199
- 200
- 208
- 210
- 200
- 207
- 240
- 269
- 260
- 263

This report indicates that, scanning outward from the submarine, the sonar sweep found depths of 199, 200, 208, 210, and so on.

The first order of business is to figure out how quickly the depth increases, just so you know what you're dealing with - you never know if the keys will get carried into deeper water by an ocean current or a fish or something.

To do this, count the number of times a depth measurement increases from the previous measurement. (There is no measurement before the first measurement.) In the example above, the changes are as follows:

- 199 (N/A - no previous measurement)
- 200 (increased)
- 208 (increased)
- 210 (increased)
- 200 (decreased)
- 207 (increased)
- 240 (increased)
- 269 (increased)
- 260 (decreased)
- 263 (increased)

In this example, there are 7 measurements that are larger than the previous measurement.

How many measurements are larger than the previous measurement?

In [35]:
with open("2021_day1.txt", "r") as f:
    lines = f.readlines()

first_val = int(lines[0])
larger = 0

for val in lines:
    val = int(val.strip())
    
    if val == first_val:
        print("{} (N/A - no previous measurement)".format(val))
    elif val < first_val:
        print("{} (decreased)".format(val))
    elif val > first_val:
        print("{} (increased)".format(val))
        larger += 1
        
    first_val = val
    
print(larger)

176 (N/A - no previous measurement)
184 (increased)
196 (increased)
199 (increased)
204 (increased)
206 (increased)
219 (increased)
215 (decreased)
216 (increased)
217 (increased)
218 (increased)
230 (increased)
231 (increased)
214 (decreased)
210 (decreased)
189 (decreased)
174 (decreased)
170 (decreased)
162 (decreased)
167 (increased)
173 (increased)
182 (increased)
177 (decreased)
179 (increased)
180 (increased)
182 (increased)
198 (increased)
201 (increased)
200 (decreased)
207 (increased)
203 (decreased)
213 (increased)
231 (increased)
222 (decreased)
223 (increased)
224 (increased)
209 (decreased)
217 (increased)
228 (increased)
236 (increased)
243 (increased)
241 (decreased)
260 (increased)
262 (increased)
258 (decreased)
260 (increased)
254 (decreased)
270 (increased)
271 (increased)
278 (increased)
264 (decreased)
263 (decreased)
262 (decreased)
260 (decreased)
261 (increased)
234 (decreased)
229 (decreased)
233 (increased)
208 (decreased)
210 (increased)
211 (increased)
210 

3820 (decreased)
3821 (increased)
3825 (increased)
3846 (increased)
3848 (increased)
3847 (decreased)
3846 (decreased)
3849 (increased)
3854 (increased)
3844 (decreased)
3860 (increased)
3859 (decreased)
3861 (increased)
3863 (increased)
3848 (decreased)
3845 (decreased)
3846 (increased)
3853 (increased)
3851 (decreased)
3850 (decreased)
3863 (increased)
3865 (increased)
3885 (increased)
3912 (increased)
3913 (increased)
3914 (increased)
3913 (decreased)
3901 (decreased)
3897 (decreased)
3927 (increased)
3928 (increased)
3927 (decreased)
3929 (increased)
3931 (increased)
3925 (decreased)
3912 (decreased)
3915 (increased)
3919 (increased)
3920 (increased)
3896 (decreased)
3900 (increased)
3904 (increased)
3909 (increased)
3919 (increased)
3922 (increased)
3923 (increased)
3925 (increased)
3944 (increased)
3938 (decreased)
3937 (decreased)
3936 (decreased)
3944 (increased)
3943 (decreased)
3942 (decreased)
3955 (increased)
3944 (decreased)
3945 (increased)
3948 (increased)
3946 (decrease

## Part 2

Considering every single measurement isn't as useful as you expected: there's just too much noise in the data.

Instead, consider sums of a three-measurement sliding window. Again considering the above example:

- 199  A      
- 200  A B    
- 208  A B C  
- 210    B C D
- 200  E   C D
- 207  E F   D
- 240  E F G  
- 269    F G H
- 260      G H
- 263        H

Start by comparing the first and second three-measurement windows. The measurements in the first window are marked A (199, 200, 208); their sum is 199 + 200 + 208 = 607. The second window is marked B (200, 208, 210); its sum is 618. The sum of measurements in the second window is larger than the sum of the first, so this first comparison increased.

Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.

In the above example, the sum of each three-measurement window is as follows:

- A: 607 (N/A - no previous sum)
- B: 618 (increased)
- C: 618 (no change)
- D: 617 (decreased)
- E: 647 (increased)
- F: 716 (increased)
- G: 769 (increased)
- H: 792 (increased)

In this example, there are 5 sums that are larger than the previous sum.

Consider sums of a three-measurement sliding window. How many sums are larger than the previous sum?

In [68]:
with open("2021_day1.txt", "r") as f:
    lines = f.readlines()
    
larger = 0

summaries = [int(lines[i]) + int(lines[i+1]) + int(lines[i+2]) for i in range(len(lines) - 2)]
first_summary = summaries[0]

for summary in summaries:
    if summary > first_summary:
        larger += 1
        
    first_summary = summary
    
print(larger)

1378
